#!/usr/bin/env python3
"""Generates the raw conformance scenarios, configs/conf-java-{agent,client}-<transport>.json,
from the case lists in raw.py, the catalogue (steps.json) and expectations/raw.json.

  python3 programs/raw/gen_conf.py            write the six configs
  python3 programs/raw/gen_conf.py --check    exit 1 if a committed config is stale or missing
  python3 programs/raw/gen_conf.py --list     print the scenarios and their case counts

conf-java-agent-<t>:  the raw client probes the Java agent (programs/java) over <t>.
conf-java-client-<t>: the Java client runs AGENT_ROLE_STEPS against the raw agent over <t>; the
                      raw agent runs AGENT_CASES against the client during the plain prompt.

expectations/raw.json has two arrays. "expectations" is read by GenConfigs.java like every
other expectations file; the raw driver is no matrix language, so it stays empty. "conformance"
holds the expected failures of these scenarios:

  { "case": "raw.invalid-params.type" | "agent.raw.id.null" | "<catalogue step id>",
    "when": { "side": "agent" | "client", "transport": "stdio" | ["http", "ws"] },
    "contains": "-32603", "see": "P2" | "peer:<sdk> <file:line>" | "spec:<where>" | "java:<file>:<line>",
    "reason": "one line" }

side "agent" selects conf-java-agent-* (the Java agent under test, case ids raw.*); side "client"
selects conf-java-client-* (the Java client under test: agent.raw.* lines from the raw agent, and
the Java client's own catalogue step ids). Omitted when keys match anything. "java:" names a Java
SDK defect that has no Phase B item yet.
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.dont_write_bytecode = True
import raw  # noqa: E402

MARKER = "GENERATED by programs/raw/gen_conf.py from raw.py, steps.json and expectations/raw.json; do not edit, regenerate."
TRANSPORTS = ("stdio", "http", "ws")
SEE = re.compile(r"^(P\d+b?|peer:\S+ \S+.*|spec:\S.*|java:\S+:\d+.*)$")
JAVA_BUILD = 'IT_ROOT="${ROOT}" MVNW="${MVNW}" ACP_VERSION="${ACP_VERSION}" CACHE="${CACHE}" ${ROOT}/programs/java/launch/build.sh'
RAW_BUILD = '${ROOT}/programs/raw/launch/build.sh'


def load(path):
    with open(os.path.join(ROOT, path)) as f:
        return json.load(f)


def entries(problems):
    doc = load("expectations/raw.json")
    if doc.get("expectations") != []:
        problems.append("expectations/raw.json: \"expectations\" must be [] (the raw driver is no matrix language)")
    out = []
    for i, e in enumerate(doc.get("conformance", [])):
        where = "expectations/raw.json conformance[%d]" % i
        for k in e:
            if k not in ("case", "when", "contains", "see", "reason", "comment"):
                problems.append("%s: unknown field %s" % (where, k))
        for k in ("case", "contains", "see", "reason"):
            if not isinstance(e.get(k), str):
                problems.append("%s: \"%s\" must be a string" % (where, k))
        when = e.get("when", {})
        for k, v in when.items():
            vals = v if isinstance(v, list) else [v]
            valid = {"side": ("agent", "client"), "transport": TRANSPORTS}.get(k)
            if valid is None:
                problems.append("%s: unknown when.%s" % (where, k))
                continue
            for x in vals:
                if x not in valid:
                    problems.append("%s: when.%s has unknown value %s" % (where, k, x))
        if isinstance(e.get("see"), str) and not SEE.match(e["see"]):
            problems.append("%s: see must be P<n>, peer:<sdk> <file:line>, spec:<where> or java:<file>:<line>" % where)
        if not str(e.get("reason", "")).strip():
            problems.append("%s: reason is empty" % where)
        out.append(dict(e, _where=where))
    return out


def matches(e, side, transport):
    for k, v in e.get("when", {}).items():
        vals = v if isinstance(v, list) else [v]
        if (side if k == "side" else transport) not in vals:
            return False
    return True


def scenario(side, t, steps, exps, problems):
    stdio = t == "stdio"
    url = {"http": " --url http://127.0.0.1:${PORT}/acp", "ws": " --url ws://127.0.0.1:${PORT}/acp"}.get(t, "")
    if side == "agent":
        # The raw client probes the Java agent.
        ids = raw.client_case_ids(t)
        client = {"name": "client", "language": "python", "role": "client", "dir": "${ROOT}/programs/raw",
                  "build": RAW_BUILD + (" && " + JAVA_BUILD if stdio else ""),
                  "run": "${ROOT}/programs/raw/launch/client.sh --transport " + t + url, "env": {}}
        if stdio:
            client["env"]["AGENT_CMD"] = "${ROOT}/programs/java/launch/agent.sh --transport stdio"
        server = {"name": "agent", "language": "java", "role": "server", "dir": "${ROOT}/programs/java",
                  "build": JAVA_BUILD, "run": "${ROOT}/programs/java/launch/agent.sh --transport " + t + " --port ${PORT}",
                  "env": {}, "ready": {"line": "READY", "timeoutSec": 60}}
        agent_lines = []
        desc = "raw client -> java agent over %s: %d raw JSON-RPC cases (generated)" % (t, len(ids))
    else:
        # The Java client runs catalogue steps against the raw agent, which probes it.
        ids = raw.agent_step_ids(t)
        client = {"name": "client", "language": "java", "role": "client", "dir": "${ROOT}/programs/java",
                  "build": JAVA_BUILD + (" && " + RAW_BUILD if stdio else ""),
                  "run": "${ROOT}/programs/java/launch/client.sh --transport " + t + url,
                  "env": {"STEPS": ",".join(ids)}}
        if stdio:
            client["env"]["AGENT_CMD"] = "${ROOT}/programs/raw/launch/agent.sh --transport stdio"
        server = {"name": "agent", "language": "python", "role": "server", "dir": "${ROOT}/programs/raw",
                  "build": RAW_BUILD, "run": "${ROOT}/programs/raw/launch/agent.sh --transport " + t + " --port ${PORT}",
                  "env": {}, "ready": {"line": "READY", "timeoutSec": 30}}
        agent_lines = ["agent.raw." + c[len("raw."):] for c in raw.agent_case_ids(t)]
        agent_lines += ["agent." + s for s in ids if isinstance(steps.get(s, {}).get("pass", {}).get("agent"), str)]
        desc = "java client -> raw agent over %s: %d catalogue steps, %d raw cases on the client (generated)" % (
            t, len(ids), len(raw.agent_case_ids(t)))
    agent_proc = "client" if stdio else "agent"
    chosen = {}
    for e in exps:
        if not matches(e, side, t):
            continue
        key = e["case"]
        if key not in ids and key not in agent_lines:
            continue
        prev = chosen.get(key)
        if prev is None or len(e.get("when", {})) > len(prev.get("when", {})):
            chosen[key] = e
    client_xfail = sum(1 for k in chosen if k in ids)
    required = [("STEP %s PASS" % a) for a in agent_lines if a not in chosen]
    xf = []
    for k, e in chosen.items():
        xf.append({"process": "client" if k in ids else agent_proc, "step": k, "contains": e["contains"],
                   "reason": e["reason"], "see": e["see"] + " [expectations/raw.json]"})
    timeout = 120 + 5 * len(ids)
    client["timeoutSec"] = timeout
    cfg = {
        "name": "conf-java-%s-%s" % (side, t),
        "description": desc,
        "timeoutSec": timeout + 120,
        "peers": [],
        "processes": ([client] if stdio else [server, client]),
        "assertions": {
            "requiredOutput": {agent_proc: required} if required else {},
            "checks": ["client RESULT pass == %d" % (len(ids) - client_xfail), "client RESULT fail == %d" % client_xfail],
            "expectedFailures": xf,
            "report": {"client": ["TIMEOUT"]},
        },
        "comment": MARKER,
    }
    if not cfg["assertions"]["requiredOutput"]:
        del cfg["assertions"]["requiredOutput"]
    return cfg, set(chosen)


def generate():
    problems = []
    steps = {s["id"]: s for s in load("steps.json")["steps"]}
    for s in raw.AGENT_ROLE_STEPS:
        if s not in steps:
            problems.append("raw.py AGENT_ROLE_STEPS: no step %s in steps.json" % s)
    exps = entries(problems)
    out = {}
    used = set()
    for side in ("agent", "client"):
        for t in TRANSPORTS:
            cfg, chosen = scenario(side, t, steps, exps, problems)
            out[cfg["name"]] = json.dumps(cfg, indent=2) + "\n"
            used |= {(e["_where"]) for e in exps if e["case"] in chosen and matches(e, side, t)}
    for e in exps:
        if e["_where"] not in used:
            problems.append("%s (%s): matches no case of any conf scenario" % (e["_where"], e.get("case")))
    return out, problems


def main(argv):
    out, problems = generate()
    if problems:
        for p in problems:
            print(p, file=sys.stderr)
        sys.exit(1)
    configs = os.path.join(ROOT, "configs")
    if "--list" in argv:
        for name, text in out.items():
            print("%s  %s" % (name, json.loads(text)["description"]))
        return
    if "--check" in argv:
        stale = []
        for name, text in out.items():
            path = os.path.join(configs, name + ".json")
            if not os.path.exists(path):
                stale.append("missing configs/%s.json" % name)
            elif open(path).read() != text:
                stale.append("stale configs/%s.json" % name)
        for f in sorted(os.listdir(configs)):
            if f.startswith("conf-java-") and f[:-5] not in out:
                stale.append("extra configs/%s" % f)
        if stale:
            print("\n".join(stale))
            print("Conformance configs are out of date: run 'python3 programs/raw/gen_conf.py'")
            sys.exit(1)
        print("Conformance configs are up to date (%d)" % len(out))
        return
    for name, text in out.items():
        with open(os.path.join(configs, name + ".json"), "w") as f:
            f.write(text)
    print("Wrote %d config(s) to %s" % (len(out), configs))


if __name__ == "__main__":
    main(sys.argv[1:])
