///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS com.fasterxml.jackson.core:jackson-databind:2.17.1
//JAVA 17+

import com.fasterxml.jackson.core.util.DefaultIndenter;
import com.fasterxml.jackson.core.util.DefaultPrettyPrinter;
import com.fasterxml.jackson.core.util.Separators;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Generates the cross-SDK cell configs from steps.json, matrix.json and expectations/*.json.
 *
 * <pre>
 *   cd integration-testing
 *   jbang GenConfigs.java                      # (re)write configs/x-*.json for the enabled languages
 *   jbang GenConfigs.java --check              # exit 1 if any generated config is stale, missing or extra
 *   jbang GenConfigs.java --list               # print the cells and their step counts, write nothing
 *   jbang GenConfigs.java --enable typescript --self --steps all   # local development (never commit the result)
 * </pre>
 *
 * Options: {@code --enable <lang,...>} treats languages as enabled; {@code --self} also writes
 * self-&lt;lang&gt;-&lt;transport&gt; cells (git-ignored); {@code --steps seed|all|<id,...>} overrides
 * matrix.json's stepSelection. Every written file carries a {@code comment} marker; --check
 * compares them with what the committed inputs produce, ignoring self-* cells.
 *
 * The output is ordinary runner configs: RunScenario, Checks, Scenario and Proc are unchanged.
 */
public class GenConfigs {

	static final ObjectMapper M = new ObjectMapper();

	static final String MARKER = "GENERATED by GenConfigs.java from steps.json, matrix.json and expectations/*.json; do not edit, regenerate.";

	static final Pattern SEE = Pattern.compile("^(P\\d+b?|peer:[a-z0-9-]+ \\S.*|spec:\\S.*)$");

	static final Set<String> WHEN_KEYS = Set.of("client", "agent", "transport", "profile");

	final Path root;

	final JsonNode steps;

	final JsonNode matrix;

	final List<Expectation> expectations = new ArrayList<>();

	final Set<String> enabled = new LinkedHashSet<>();

	final List<String> problems = new ArrayList<>();

	String stepSelection;

	boolean self;

	record Expectation(String file, int index, String step, Map<String, List<String>> when, String contains, String see,
			String reason) {

		boolean matches(Cell c) {
			for (Map.Entry<String, List<String>> e : when.entrySet()) {
				String v = switch (e.getKey()) {
					case "client" -> c.client;
					case "agent" -> c.agent;
					case "transport" -> c.transport;
					default -> c.profile;
				};
				if (!e.getValue().contains(v)) {
					return false;
				}
			}
			return true;
		}

	}

	record Cell(String name, String client, String agent, String transport, String profile) {
	}

	public static void main(String... args) throws Exception {
		boolean check = false;
		boolean list = false;
		String steps = null;
		List<String> enable = new ArrayList<>();
		boolean self = false;
		for (int i = 0; i < args.length; i++) {
			switch (args[i]) {
				case "--check" -> check = true;
				case "--list" -> list = true;
				case "--self" -> self = true;
				case "--steps" -> steps = args[++i];
				case "--enable" -> enable.addAll(List.of(args[++i].split(",")));
				case "-h", "--help" -> {
					System.out.println("Usage: jbang GenConfigs.java [--check | --list] [--enable <lang,...>] [--self] [--steps seed|all|<id,...>]");
					return;
				}
				default -> {
					System.err.println("Unknown option " + args[i]);
					System.exit(2);
				}
			}
		}
		if (check && (self || steps != null || !enable.isEmpty())) {
			System.err.println("--check compares with the committed inputs only; drop --self, --steps and --enable");
			System.exit(2);
		}
		GenConfigs g = new GenConfigs(root());
		g.self = self;
		g.stepSelection = steps != null ? steps : g.matrix.path("stepSelection").asText("seed");
		for (String l : enable) {
			if (!g.matrix.path("languages").has(l)) {
				System.err.println("--enable: unknown language " + l);
				System.exit(2);
			}
			g.enabled.add(l);
		}
		g.validate();
		if (!g.problems.isEmpty()) {
			g.problems.forEach(p -> System.err.println("ERROR " + p));
			System.exit(2);
		}
		Map<String, String> generated = g.generate();
		if (list) {
			return;
		}
		System.exit(check ? g.check(generated) : g.write(generated));
	}

	static Path root() {
		Path cwd = Path.of("").toAbsolutePath();
		for (Path p : List.of(cwd, cwd.resolve("integration-testing"))) {
			if (Files.exists(p.resolve("GenConfigs.java")) && Files.exists(p.resolve("steps.json"))) {
				return p;
			}
		}
		throw new IllegalStateException("Run from integration-testing/ or the repository root");
	}

	GenConfigs(Path root) throws Exception {
		this.root = root;
		this.steps = M.readTree(root.resolve("steps.json").toFile());
		this.matrix = M.readTree(root.resolve("matrix.json").toFile());
		matrix.path("languages").fields().forEachRemaining(e -> {
			if (e.getValue().path("enabled").asBoolean(false)) {
				enabled.add(e.getKey());
			}
		});
		Path dir = root.resolve("expectations");
		if (Files.isDirectory(dir)) {
			try (Stream<Path> s = Files.list(dir)) {
				for (Path f : s.filter(p -> p.toString().endsWith(".json")).sorted().toList()) {
					readExpectations(f);
				}
			}
		}
	}

	void readExpectations(Path f) throws Exception {
		String file = "expectations/" + f.getFileName();
		JsonNode doc = M.readTree(f.toFile());
		JsonNode arr = doc.path("expectations");
		if (!arr.isArray()) {
			problems.add(file + ": needs an \"expectations\" array");
			return;
		}
		for (int i = 0; i < arr.size(); i++) {
			JsonNode e = arr.get(i);
			String where = file + "[" + i + "]";
			Map<String, List<String>> when = new TreeMap<>();
			e.path("when").fields().forEachRemaining(w -> {
				List<String> vals = new ArrayList<>();
				if (w.getValue().isArray()) {
					w.getValue().forEach(v -> vals.add(v.asText()));
				}
				else {
					vals.add(w.getValue().asText());
				}
				when.put(w.getKey(), vals);
			});
			for (Iterator<String> it = e.fieldNames(); it.hasNext();) {
				String k = it.next();
				if (!Set.of("step", "when", "contains", "see", "reason", "comment").contains(k)) {
					problems.add(where + ": unknown field " + k);
				}
			}
			for (String k : List.of("step", "contains", "see", "reason")) {
				if (!e.path(k).isTextual()) {
					problems.add(where + ": \"" + k + "\" must be a string" + (k.equals("contains") ? " (\"\" for any)" : ""));
				}
			}
			expectations.add(new Expectation(file, i, e.path("step").asText(), when, e.path("contains").asText(),
					e.path("see").asText(), e.path("reason").asText()));
		}
	}

	// ---------------------------------------------------------------- validation

	void validate() {
		Set<String> ids = new LinkedHashSet<>();
		Set<String> langs = new LinkedHashSet<>();
		matrix.path("languages").fieldNames().forEachRemaining(langs::add);
		Set<String> transports = new LinkedHashSet<>();
		matrix.path("transports").forEach(t -> transports.add(t.asText()));
		Set<String> profiles = new LinkedHashSet<>();
		matrix.path("profiles").fieldNames().forEachRemaining(profiles::add);
		for (JsonNode s : steps.path("steps")) {
			String id = s.path("id").asText("");
			if (id.isEmpty() || !id.matches("[a-z][a-z0-9_.-]*")) {
				problems.add("steps.json: bad step id '" + id + "'");
			}
			if (!ids.add(id)) {
				problems.add("steps.json: duplicate step id " + id);
			}
			if (!s.path("pass").path("client").isTextual() || !s.path("client").isTextual()) {
				problems.add("steps.json: step " + id + " needs \"client\" and \"pass.client\"");
			}
			if (!profiles.contains(profile(s))) {
				problems.add("steps.json: step " + id + " has unknown profile " + profile(s));
			}
			for (String t : stepTransports(s)) {
				if (!transports.contains(t)) {
					problems.add("steps.json: step " + id + " has unknown transport " + t);
				}
			}
			s.path("only").fields().forEachRemaining(o -> {
				if (!Set.of("client", "agent").contains(o.getKey())) {
					problems.add("steps.json: step " + id + " has unknown only." + o.getKey());
				}
				o.getValue().forEach(v -> {
					if (!langs.contains(v.asText())) {
						problems.add("steps.json: step " + id + " names unknown language " + v.asText());
					}
				});
			});
		}
		String first = steps.path("conventions").path("first").asText();
		String last = steps.path("conventions").path("last").asText();
		if (!ids.contains(first) || !ids.contains(last)) {
			problems.add("steps.json: conventions.first/last must name steps");
		}
		if (!Set.of("seed", "all").contains(stepSelection)) {
			for (String id : stepSelection.split(",")) {
				if (!ids.contains(id)) {
					problems.add("--steps: unknown step " + id);
				}
			}
		}
		for (JsonNode p : matrix.path("pairs")) {
			for (JsonNode l : p) {
				if (!langs.contains(l.asText())) {
					problems.add("matrix.json: pair names unknown language " + l.asText());
				}
			}
		}
		matrix.path("self").forEach(l -> {
			if (!langs.contains(l.asText())) {
				problems.add("matrix.json: self names unknown language " + l.asText());
			}
		});
		matrix.path("facts").forEach(f -> checkWhen("matrix.json fact", f.path("when"), langs, transports, profiles));
		List<Cell> universe = cells(true, true);
		for (Expectation x : expectations) {
			String where = x.file + "[" + x.index + "] (" + x.step + ")";
			String id = x.step.startsWith("agent.") ? x.step.substring(6) : x.step;
			JsonNode s = step(id);
			if (s == null) {
				problems.add(where + ": no step " + id + " in steps.json");
				continue;
			}
			if (x.step.startsWith("agent.") && !s.path("pass").path("agent").isTextual()) {
				problems.add(where + ": step " + id + " has no agent-side assertion");
			}
			ObjectNode w = M.createObjectNode();
			x.when.forEach((k, v) -> {
				ArrayNode a = w.putArray(k);
				v.forEach(a::add);
			});
			checkWhen(where, w, langs, transports, profiles);
			if (!SEE.matcher(x.see).matches()) {
				problems.add(where + ": see must be a P-item (P3, P1b), \"peer:<sdk> <file:line>\" or \"spec:<where>\", got '"
						+ x.see + "'");
			}
			if (x.reason.isBlank()) {
				problems.add(where + ": reason is empty");
			}
			if (universe.stream().noneMatch(c -> x.matches(c) && cellSteps(c, "all").contains(id))) {
				problems.add(where + ": matches no cell of the full matrix (check when and the step's transports/only)");
			}
		}
	}

	void checkWhen(String where, JsonNode when, Set<String> langs, Set<String> transports, Set<String> profiles) {
		when.fields().forEachRemaining(w -> {
			if (!WHEN_KEYS.contains(w.getKey())) {
				problems.add(where + ": unknown when." + w.getKey());
				return;
			}
			Set<String> valid = switch (w.getKey()) {
				case "client", "agent" -> langs;
				case "transport" -> transports;
				default -> profiles;
			};
			List<String> vals = new ArrayList<>();
			if (w.getValue().isArray()) {
				w.getValue().forEach(v -> vals.add(v.asText()));
			}
			else {
				vals.add(w.getValue().asText());
			}
			for (String v : vals) {
				if (!valid.contains(v)) {
					problems.add(where + ": when." + w.getKey() + " has unknown value " + v);
				}
			}
		});
	}

	// ---------------------------------------------------------------- cells

	/** Every cell of the matrix; enabled languages only unless {@code all}. */
	List<Cell> cells(boolean all, boolean withSelf) {
		List<Cell> out = new ArrayList<>();
		List<String[]> pairs = new ArrayList<>();
		for (JsonNode p : matrix.path("pairs")) {
			pairs.add(new String[] { p.get(0).asText(), p.get(1).asText(), "x-" + p.get(0).asText() + "-" + p.get(1).asText() });
		}
		if (withSelf) {
			for (JsonNode l : matrix.path("self")) {
				pairs.add(new String[] { l.asText(), l.asText(), "self-" + l.asText() });
			}
		}
		for (String[] p : pairs) {
			if (!all && !(enabled.contains(p[0]) && enabled.contains(p[1]))) {
				continue;
			}
			for (JsonNode t : matrix.path("transports")) {
				String tr = t.asText();
				if (!lang(p[0]).path("transports").toString().contains("\"" + tr + "\"")
						|| !lang(p[1]).path("transports").toString().contains("\"" + tr + "\"")) {
					continue;
				}
				for (Iterator<Map.Entry<String, JsonNode>> it = matrix.path("profiles").fields(); it.hasNext();) {
					Map.Entry<String, JsonNode> pr = it.next();
					out.add(new Cell(p[2] + "-" + tr + pr.getValue().path("suffix").asText(), p[0], p[1], tr, pr.getKey()));
				}
			}
		}
		return out;
	}

	/** The step ids a cell runs, in catalogue order; empty if the profile adds nothing. */
	List<String> cellSteps(Cell c, String selection) {
		String first = steps.path("conventions").path("first").asText();
		String last = steps.path("conventions").path("last").asText();
		Set<String> picked = selection.equals("seed") || selection.equals("all") ? null
				: new LinkedHashSet<>(List.of(selection.split(",")));
		List<String> out = new ArrayList<>();
		boolean any = false;
		for (JsonNode s : steps.path("steps")) {
			String id = s.path("id").asText();
			boolean mandatory = id.equals(first) || id.equals(last);
			boolean selected = mandatory || switch (selection) {
				case "all" -> true;
				case "seed" -> s.path("seed").asBoolean(false);
				default -> picked.contains(id);
			};
			if (!selected || !(mandatory || profile(s).equals(c.profile)) || !stepTransports(s).contains(c.transport)) {
				continue;
			}
			JsonNode only = s.path("only");
			if (only.has("client") && !only.path("client").toString().contains("\"" + c.client + "\"")
					|| only.has("agent") && !only.path("agent").toString().contains("\"" + c.agent + "\"")) {
				continue;
			}
			out.add(id);
			any |= !mandatory;
		}
		return any ? out : List.of();
	}

	Map<String, String> generate() throws Exception {
		Map<String, String> out = new TreeMap<>();
		for (Cell c : cells(false, self)) {
			List<String> ids = cellSteps(c, stepSelection);
			if (ids.isEmpty()) {
				continue;
			}
			ObjectNode cfg = config(c, ids);
			out.put(c.name, write(cfg));
			System.out.printf("  %-40s %3d steps, %d expected failure(s)%n", c.name, ids.size(),
					cfg.path("assertions").path("expectedFailures").size());
		}
		return out;
	}

	ObjectNode config(Cell c, List<String> ids) {
		boolean stdio = c.transport.equals("stdio");
		String agentProc = stdio ? "client" : "agent";
		ObjectNode cfg = M.createObjectNode();
		cfg.put("name", c.name);
		cfg.put("description", c.client + " client -> " + c.agent + " agent over " + c.transport + ", " + c.profile
				+ " profile, " + ids.size() + " steps (generated)");
		int clientTimeout = 120 + 5 * ids.size();
		cfg.put("timeoutSec", clientTimeout + 120);
		ArrayNode peers = cfg.putArray("peers");
		Set<String> peerSet = new LinkedHashSet<>();
		lang(c.client).path("peers").forEach(p -> peerSet.add(p.asText()));
		lang(c.agent).path("peers").forEach(p -> peerSet.add(p.asText()));
		peerSet.forEach(peers::add);

		Map<String, String> env = new LinkedHashMap<>();
		lang(c.client).path("env").fields().forEachRemaining(e -> env.put(e.getKey(), e.getValue().asText()));
		lang(c.agent).path("env").fields().forEachRemaining(e -> env.put(e.getKey(), e.getValue().asText()));

		ArrayNode procs = cfg.putArray("processes");
		if (!stdio) {
			ObjectNode a = procs.addObject();
			a.put("name", "agent");
			a.put("language", c.agent);
			a.put("role", "server");
			a.put("dir", "${ROOT}/" + lang(c.agent).path("dir").asText());
			a.put("build", build(c.agent));
			a.put("run", launcher(c.agent, "agent") + " --transport " + c.transport + " --port ${PORT}");
			ObjectNode aenv = a.putObject("env");
			env.forEach(aenv::put);
			ObjectNode ready = a.putObject("ready");
			ready.put("line", "READY");
			ready.put("timeoutSec", lang(c.agent).path("readyTimeoutSec").asInt(60));
		}
		ObjectNode cl = procs.addObject();
		cl.put("name", "client");
		cl.put("language", c.client);
		cl.put("role", "client");
		cl.put("dir", "${ROOT}/" + lang(c.client).path("dir").asText());
		String build = build(c.client);
		if (stdio && !c.agent.equals(c.client)) {
			build = build + " && " + build(c.agent);
		}
		cl.put("build", build);
		String url = switch (c.transport) {
			case "http" -> " --url http://127.0.0.1:${PORT}/acp";
			case "ws" -> " --url ws://127.0.0.1:${PORT}/acp";
			default -> "";
		};
		cl.put("run", launcher(c.client, "client") + " --transport " + c.transport + url);
		ObjectNode cenv = cl.putObject("env");
		cenv.put("STEPS", String.join(",", ids));
		if (stdio) {
			cenv.put("AGENT_CMD", launcher(c.agent, "agent") + " --transport stdio");
		}
		env.forEach(cenv::put);
		cl.put("timeoutSec", clientTimeout);

		// Expected failures: per step key (client step id or agent.<id>), the most specific entry wins.
		Map<String, Expectation> chosen = new LinkedHashMap<>();
		for (String id : ids) {
			for (String key : List.of(id, "agent." + id)) {
				Expectation best = null;
				for (Expectation x : expectations) {
					if (x.step.equals(key) && x.matches(c) && (best == null || rank(x, c) > rank(best, c))) {
						best = x;
					}
				}
				if (best != null) {
					chosen.put(key, best);
				}
			}
		}
		ObjectNode as = cfg.putObject("assertions");
		Map<String, Set<String>> required = new LinkedHashMap<>();
		Map<String, Set<String>> forbidden = new LinkedHashMap<>();
		Map<String, Set<String>> patterns = new LinkedHashMap<>();
		for (String id : ids) {
			JsonNode s = step(id);
			if (s.path("pass").path("agent").isTextual() && !chosen.containsKey(id) && !chosen.containsKey("agent." + id)) {
				required.computeIfAbsent(agentProc, k -> new LinkedHashSet<>()).add("STEP agent." + id + " PASS");
			}
		}
		for (JsonNode f : matrix.path("facts")) {
			if (!factMatches(f.path("when"), c)) {
				continue;
			}
			mergeFact(f.path("requiredOutput"), required, agentProc);
			mergeFact(f.path("forbiddenOutput"), forbidden, agentProc);
			mergeFact(f.path("requiredPatterns"), patterns, agentProc);
		}
		putLines(as, "requiredOutput", required);
		putLines(as, "forbiddenOutput", forbidden);
		putLines(as, "requiredPatterns", patterns);
		long clientXfail = chosen.keySet().stream().filter(k -> !k.startsWith("agent.")).count();
		ArrayNode checks = as.putArray("checks");
		checks.add("client RESULT pass == " + (ids.size() - clientXfail));
		checks.add("client RESULT fail == " + clientXfail);
		ArrayNode xf = as.putArray("expectedFailures");
		chosen.forEach((key, x) -> {
			ObjectNode o = xf.addObject();
			o.put("process", key.startsWith("agent.") ? agentProc : "client");
			o.put("step", key);
			o.put("contains", x.contains);
			o.put("reason", x.reason);
			o.put("see", x.see + " [" + x.file + "]");
		});
		ObjectNode report = as.putObject("report");
		report.putArray("client").add("TIMEOUT");
		cfg.put("comment", MARKER);
		return cfg;
	}

	/** Higher is more specific: more when keys, then the client's file, then the agent's file, then file order. */
	static int rank(Expectation x, Cell c) {
		int r = x.when.size() * 10_000;
		if (x.file.equals("expectations/" + c.client + ".json")) {
			r += 2_000;
		}
		else if (x.file.equals("expectations/" + c.agent + ".json")) {
			r += 1_000;
		}
		return r - x.index;
	}

	static boolean factMatches(JsonNode when, Cell c) {
		for (Iterator<Map.Entry<String, JsonNode>> it = when.fields(); it.hasNext();) {
			Map.Entry<String, JsonNode> w = it.next();
			String v = switch (w.getKey()) {
				case "client" -> c.client;
				case "agent" -> c.agent;
				case "transport" -> c.transport;
				default -> c.profile;
			};
			boolean ok = w.getValue().isArray() ? w.getValue().toString().contains("\"" + v + "\"")
					: w.getValue().asText().equals(v);
			if (!ok) {
				return false;
			}
		}
		return true;
	}

	static void mergeFact(JsonNode byRole, Map<String, Set<String>> into, String agentProc) {
		byRole.fields().forEachRemaining(e -> {
			String proc = e.getKey().equals("agent") ? agentProc : e.getKey();
			e.getValue().forEach(v -> into.computeIfAbsent(proc, k -> new LinkedHashSet<>()).add(v.asText()));
		});
	}

	static void putLines(ObjectNode as, String field, Map<String, Set<String>> lines) {
		if (lines.isEmpty()) {
			return;
		}
		ObjectNode o = as.putObject(field);
		lines.forEach((proc, set) -> {
			ArrayNode a = o.putArray(proc);
			set.forEach(a::add);
		});
	}

	String build(String language) {
		StringBuilder sb = new StringBuilder("IT_ROOT=\"${ROOT}\" MVNW=\"${MVNW}\" ACP_VERSION=\"${ACP_VERSION}\" CACHE=\"${CACHE}\"");
		lang(language).path("env").fields().forEachRemaining(e -> sb.append(' ').append(e.getKey()).append("=\"")
			.append(e.getValue().asText()).append('"'));
		return sb.append(" ${ROOT}/").append(lang(language).path("dir").asText()).append("/launch/build.sh").toString();
	}

	String launcher(String language, String role) {
		return "${ROOT}/" + lang(language).path("dir").asText() + "/launch/" + role + ".sh";
	}

	JsonNode lang(String l) {
		return matrix.path("languages").path(l);
	}

	JsonNode step(String id) {
		for (JsonNode s : steps.path("steps")) {
			if (s.path("id").asText().equals(id)) {
				return s;
			}
		}
		return null;
	}

	static String profile(JsonNode s) {
		return s.path("profile").asText("stable");
	}

	List<String> stepTransports(JsonNode s) {
		List<String> out = new ArrayList<>();
		(s.has("transports") ? s.path("transports") : matrix.path("transports")).forEach(t -> out.add(t.asText()));
		return out;
	}

	// ---------------------------------------------------------------- output

	static String write(ObjectNode cfg) throws Exception {
		DefaultPrettyPrinter pp = new DefaultPrettyPrinter()
			.withSeparators(Separators.createDefaultInstance()
				.withObjectFieldValueSpacing(Separators.Spacing.AFTER)
				.withArrayEmptySeparator("")
				.withObjectEmptySeparator(""));
		pp.indentArraysWith(DefaultIndenter.SYSTEM_LINEFEED_INSTANCE.withLinefeed("\n"));
		pp.indentObjectsWith(DefaultIndenter.SYSTEM_LINEFEED_INSTANCE.withLinefeed("\n"));
		return M.writer(pp).writeValueAsString(cfg) + "\n";
	}

	Set<String> generatedOnDisk() throws Exception {
		Set<String> out = new LinkedHashSet<>();
		try (Stream<Path> s = Files.list(root.resolve("configs"))) {
			for (Path p : s.filter(p -> p.toString().endsWith(".json")).sorted().toList()) {
				if (Files.readString(p).contains(MARKER)) {
					out.add(p.getFileName().toString().replaceFirst("\\.json$", ""));
				}
			}
		}
		return out;
	}

	int write(Map<String, String> generated) throws Exception {
		for (Map.Entry<String, String> e : generated.entrySet()) {
			Files.writeString(root.resolve("configs").resolve(e.getKey() + ".json"), e.getValue());
		}
		for (String name : generatedOnDisk()) {
			if (!generated.containsKey(name)) {
				Files.delete(root.resolve("configs").resolve(name + ".json"));
				System.out.println("  removed stale configs/" + name + ".json");
			}
		}
		System.out.println("Wrote " + generated.size() + " config(s) to " + root.resolve("configs"));
		return 0;
	}

	int check(Map<String, String> generated) throws Exception {
		List<String> stale = new ArrayList<>();
		for (Map.Entry<String, String> e : generated.entrySet()) {
			Path p = root.resolve("configs").resolve(e.getKey() + ".json");
			if (!Files.exists(p)) {
				stale.add("missing configs/" + e.getKey() + ".json");
			}
			else if (!Files.readString(p).equals(e.getValue())) {
				stale.add("stale configs/" + e.getKey() + ".json");
			}
		}
		for (String name : generatedOnDisk()) {
			if (!generated.containsKey(name) && !name.startsWith("self-")) {
				stale.add("extra configs/" + name + ".json (not produced by the committed inputs)");
			}
		}
		if (stale.isEmpty()) {
			System.out.println("Generated configs are up to date (" + generated.size() + ")");
			return 0;
		}
		stale.forEach(s -> System.out.println("  " + s));
		System.out.println("Generated configs are out of date: run 'jbang GenConfigs.java' in integration-testing/ and commit");
		return 1;
	}

}
