package com.agentclientprotocol.conformance;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import io.github.markpollack.judge.ai.model.EvalModel;
import io.github.markpollack.judge.ai.model.EvalModelRequest;
import io.github.markpollack.judge.ai.model.EvalModelResponse;
import io.github.markpollack.judge.ai.requirements.NativeRequirementCodecs;
import io.github.markpollack.judge.ai.requirements.Rfc2119Requirement;
import io.github.markpollack.judge.judgment.Check;
import io.github.markpollack.judge.judgment.JudgmentStatus;
import io.github.markpollack.judge.verdict.Verdict;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Offline falsification of the harness over the REAL roster with SYNTHETIC answers.
 *
 * <p>Every response here is generated by the test to exercise the wiring and the producer's
 * response semantics. None of it is an ACP judgment, and nothing here is stored as a recording.
 */
class AcpProtocolHarnessTest {

    static final String SDK = "5bb2cf62d2349fb9c47ec9ba8ad0a27762713e59";
    static final String SYNTHETIC_HEADER = "SYNTHETIC FIXTURE: generated by AcpProtocolHarnessTest, not an ACP judgment\n";

    static AcpRequirementRoster roster;

    @BeforeAll
    static void load() {
        roster = AcpRequirementRoster.load(Path.of("spec"));
    }

    static EvalModel answering(AtomicInteger calls, AtomicReference<String> request, String text) {
        return r -> {
            calls.incrementAndGet();
            request.set(AcpRunCapture.requestText(r));
            return new EvalModelResponse(text, "synthetic", null, Map.of("fixture", "synthetic"), true);
        };
    }

    /** One synthetic line per roster item, covering PASS, NOT_APPLICABLE (conditional only) and CANNOT_DETERMINE. */
    static String completeSyntheticAnswer(String failId) {
        StringBuilder text = new StringBuilder(SYNTHETIC_HEADER);
        int i = 0;
        for (Rfc2119Requirement requirement : roster.requirements()) {
            String id = requirement.id();
            String line;
            if (id.equals(failId)) {
                line = id + ": FAIL - synthetic violation citing acp-core/src/main/java/Example.java:1";
            }
            else if (requirement.specification().applicability() != null && i % 3 == 0) {
                line = id + ": NOT_APPLICABLE - synthetic: the declared condition does not hold in this fixture";
            }
            else if (i % 5 == 0) {
                line = id + ": CANNOT_DETERMINE - synthetic: insufficient evidence in this fixture";
            }
            else {
                line = id + ": PASS - synthetic support citing acp-core/src/main/java/Example.java:" + (i + 1);
            }
            text.append(line).append('\n');
            i++;
        }
        return text.toString();
    }

    @Test
    void theCompleteRosterReachesOneBackendExecutionUnchangedBehindTheAcpPreamble() {
        AtomicInteger calls = new AtomicInteger();
        AtomicReference<String> delivered = new AtomicReference<>();
        EvalModel runtime = new AcpAuditContext(answering(calls, delivered, completeSyntheticAnswer(null)), SDK,
                roster.protocolCommit(), roster.revision());
        Verdict verdict = AcpProtocolConformanceDemo.configuredJury(runtime, roster).vote();
        assertThat(calls).hasValue(1);
        String request = delivered.get();
        assertThat(request).startsWith("Assess the ACP Java SDK at " + SDK);
        assertThat(request).contains("derived from " + roster.protocolCommit());
        assertThat(request).contains("Answer every one of the 240 constraints");
        for (Rfc2119Requirement requirement : roster.requirements()) {
            assertThat(request).as("full clause of %s reaches the request", requirement.id())
                    .contains(requirement.id() + ": " + requirement.specification().keyword() + " "
                            + requirement.specification().requirement());
            assertThat(request).contains("Configured requirement: " + requirement.id() + "; revision: "
                    + requirement.revision() + "; source: " + requirement.source().artifact().id());
        }
        assertThat(request).contains("NOT_APPLICABLE is available for these constraints only");
        assertThat(verdict.roster()).hasSize(240);
        assertThat(verdict.compositeAttempts()).hasSize(240);
        assertThat(verdict.invocations()).hasSize(1);
        assertThat(RosterSummary.unbound(verdict)).isZero();
    }

    @Test
    void aCompleteSyntheticAnswerYieldsTheExpectedStatusPopulationAndSharedInvocation() {
        AtomicInteger calls = new AtomicInteger();
        String answer = completeSyntheticAnswer("ACP-V1-TRANSPORT-UTF8");
        EvalModel runtime = new AcpAuditContext(answering(calls, new AtomicReference<>(), answer), SDK,
                roster.protocolCommit(), roster.revision());
        Verdict verdict = AcpProtocolConformanceDemo.configuredJury(runtime, roster).vote();
        Map<JudgmentStatus, Long> counts = RosterSummary.counts(verdict);
        long expectedNa = answer.lines().filter(l -> l.contains(": NOT_APPLICABLE")).count();
        long expectedAbstain = answer.lines().filter(l -> l.contains(": CANNOT_DETERMINE")).count();
        long expectedPass = answer.lines().filter(l -> l.contains(": PASS")).count();
        assertThat(counts.get(JudgmentStatus.FAIL)).isEqualTo(1L);
        assertThat(counts.get(JudgmentStatus.NOT_APPLICABLE)).isEqualTo(expectedNa);
        assertThat(counts.get(JudgmentStatus.ABSTAIN)).isEqualTo(expectedAbstain);
        assertThat(counts.get(JudgmentStatus.PASS)).isEqualTo(expectedPass);
        assertThat(counts.get(JudgmentStatus.ERROR)).isZero();
        assertThat(expectedNa).isPositive();
        assertThat(verdict.conclusion()).isEqualTo(Verdict.Conclusion.FAIL);
        String root = verdict.invocations().getFirst().id();
        for (int i = 0; i < 240; i++) {
            Rfc2119Requirement requirement = roster.requirements().get(i);
            var child = verdict.compositeAttempts().get(i).verdict().individual().getFirst();
            assertThat(child.requirement()).isSameAs(requirement);
            assertThat(child.invocationIds()).containsExactly(root);
        }
        List<Check> failed = RosterSummary.checks(verdict).stream()
                .filter(c -> c.judgment().status() == JudgmentStatus.FAIL).toList();
        assertThat(failed).extracting(Check::id).containsExactly("ACP-V1-TRANSPORT-UTF8");
        assertThat(calls).hasValue(1);
    }

    /**
     * Measured 2026-10-08 against producer b7d2d88: one V6 document of the 240-item full-text verdict is about
     * 1.7 MB against VerdictCodec.MAXIMUM_BYTES = 1,048,576 and is refused. The verdict is therefore retained as
     * V6 parts, each under the bound, and reopened through the producer's codec into a Verdict equal to the
     * one that was voted.
     */
    @Test
    void theWholeRosterVerdictIsRetainedAsV6PartsUnderTheBoundAndReopensEqual(@TempDir Path temp) throws IOException {
        Verdict verdict = vote(completeSyntheticAnswer("ACP-V1-TRANSPORT-UTF8"));
        assertThatThrownBy(() -> NativeRequirementCodecs.codec().write(verdict))
                .isInstanceOf(io.github.markpollack.judge.portable.PreservationLimitException.class);
        RetainedVerdicts.Retained retained = RetainedVerdicts.write(verdict, temp);
        assertThat(retained.format()).isEqualTo("v6-parts");
        assertThat(retained.parts()).isGreaterThan(1);
        try (var files = Files.list(temp.resolve("verdict-v6-parts"))) {
            for (Path part : files.toList()) {
                assertThat(Files.size(part)).as("%s under the producer bound", part).isLessThanOrEqualTo(1048576L);
            }
        }
        Verdict reopened = RetainedVerdicts.read(temp);
        assertThat(reopened).isEqualTo(verdict);
        assertThat(reopened.conclusion()).isEqualTo(Verdict.Conclusion.FAIL);
        assertThat(RosterSummary.counts(reopened)).isEqualTo(RosterSummary.counts(verdict));
        assertThat(reopened.invocations()).isEqualTo(verdict.invocations());
    }

    @Test
    void aRefusedOrIncompleteRunIsRetainedAndReopensEqualToo(@TempDir Path temp) {
        EvalModel runtime = AcpJudgeBackends.replay(temp.resolve("runs"), "no-such-run", roster, SDK);
        Verdict verdict = AcpProtocolConformanceDemo.configuredJury(runtime, roster).vote();
        RetainedVerdicts.write(verdict, temp.resolve("retained"));
        Verdict reopened = RetainedVerdicts.read(temp.resolve("retained"));
        assertThat(reopened).isEqualTo(verdict);
        assertThat(RosterSummary.counts(reopened).get(JudgmentStatus.ERROR)).isEqualTo(240L);
    }

    /** The V6 mechanism itself works for a sub-roster: this is a serialization check, not a conformance run. */
    @Test
    void v6RoundTripWorksForASubRosterSoTheConstraintIsSizeOnly() {
        List<Rfc2119Requirement> sub = roster.requirements().subList(0, 100);
        String answer = completeSyntheticAnswer("ACP-V1-INIT-AGENT-RESPONSE").lines()
                .filter(l -> sub.stream().anyMatch(r -> l.startsWith(r.id() + ":")))
                .reduce("", (a, b) -> a + b + "\n");
        EvalModel runtime = new AcpAuditContext(answering(new AtomicInteger(), new AtomicReference<>(), answer), SDK,
                roster.protocolCommit(), roster.revision());
        Verdict verdict = io.github.markpollack.judge.ai.requirements.Rfc2119Jury.builder().runtime(runtime)
                .requirements(sub).build().vote();
        var codec = NativeRequirementCodecs.codec();
        Verdict reopened = codec.read(codec.write(verdict));
        assertThat(reopened).isEqualTo(verdict);
        assertThat(reopened.conclusion()).isEqualTo(Verdict.Conclusion.FAIL);
        assertThat(reopened.roster()).hasSize(100);
    }

    @Test
    void aSmallVerdictIsRetainedAsOneV6DocumentAndReopensEqual(@TempDir Path temp) {
        List<Rfc2119Requirement> sub = roster.requirements().subList(0, 40);
        String answer = completeSyntheticAnswer(null).lines()
                .filter(l -> sub.stream().anyMatch(r -> l.startsWith(r.id() + ":")))
                .reduce("", (a, b) -> a + b + "\n");
        EvalModel runtime = new AcpAuditContext(answering(new AtomicInteger(), new AtomicReference<>(), answer), SDK,
                roster.protocolCommit(), roster.revision());
        Verdict verdict = io.github.markpollack.judge.ai.requirements.Rfc2119Jury.builder().runtime(runtime)
                .requirements(sub).build().vote();
        RetainedVerdicts.Retained retained = RetainedVerdicts.write(verdict, temp);
        assertThat(retained.format()).isEqualTo("v6");
        assertThat(RetainedVerdicts.read(temp)).isEqualTo(verdict);
    }

    @Test
    void notApplicableOnAnUnconditionalRequirementIsAProtocolErrorNotAnExclusion() {
        String answer = replaceLine(completeSyntheticAnswer(null), "ACP-V1-OVERVIEW-ABSOLUTE-PATHS",
                "ACP-V1-OVERVIEW-ABSOLUTE-PATHS: NOT_APPLICABLE - synthetic illegal exclusion");
        Verdict verdict = vote(answer);
        // the producer keeps the model's answer as the item's reported disposition ...
        Check check = check(verdict, "ACP-V1-OVERVIEW-ABSOLUTE-PATHS");
        assertThat(check.judgment().status()).isEqualTo(JudgmentStatus.NOT_APPLICABLE);
        // ... but an exclusion the roster never authorized is not accepted: the item stays unestablished
        var attempt = verdict.compositeAttempts().getFirst();
        assertThat(attempt.name()).isEqualTo("ACP-V1-OVERVIEW-ABSOLUTE-PATHS");
        assertThat(attempt.verdict().conclusion()).isEqualTo(Verdict.Conclusion.INCONCLUSIVE);
        assertThat(verdict.conclusion()).isEqualTo(Verdict.Conclusion.INCONCLUSIVE);
        assertThat(RosterSummary.counts(verdict).get(JudgmentStatus.FAIL)).isZero();
    }

    @Test
    void malformedDuplicateMissingAndUnknownAnswersAreInstrumentFailuresNotSubjectViolations() {
        String answer = completeSyntheticAnswer(null);
        // malformed: no colon anywhere on the line (a colon in a citation would make it an undeclared id instead)
        answer = replaceLine(answer, "ACP-V1-TRANSPORT-UTF8", "ACP-V1-TRANSPORT-UTF8 PASS - synthetic line without a colon");
        // duplicate
        answer = answer + "ACP-V1-PLAN-REPORT: PASS - synthetic second answer\n";
        // missing: drop one line entirely
        answer = answer.lines().filter(l -> !l.startsWith("ACP-V1-FS-AGENT-CHECK-CAPABILITY:"))
                .reduce("", (a, b) -> a + b + "\n");
        // unknown id
        answer = answer + "ACP-V1-NOT-IN-ROSTER: FAIL - synthetic answer to an undeclared requirement\n";
        Verdict verdict = vote(answer);
        Map<JudgmentStatus, Long> counts = RosterSummary.counts(verdict);
        assertThat(counts.get(JudgmentStatus.FAIL)).as("no subject violation is manufactured").isZero();
        assertThat(check(verdict, "ACP-V1-TRANSPORT-UTF8").judgment().status()).isEqualTo(JudgmentStatus.ERROR);
        assertThat(check(verdict, "ACP-V1-TRANSPORT-UTF8").judgment().reasoning()).contains("missing colon");
        assertThat(check(verdict, "ACP-V1-PLAN-REPORT").judgment().status()).isEqualTo(JudgmentStatus.ERROR);
        assertThat(check(verdict, "ACP-V1-PLAN-REPORT").judgment().reasoning()).contains("more than once");
        assertThat(check(verdict, "ACP-V1-FS-AGENT-CHECK-CAPABILITY").judgment().status()).isEqualTo(JudgmentStatus.ERROR);
        assertThat(check(verdict, "ACP-V1-FS-AGENT-CHECK-CAPABILITY").judgment().reasoning()).contains("No answer was recorded");
        // an undeclared answer unbinds the protocol: every attempt is stage-failed, not USED
        assertThat(RosterSummary.unbound(verdict)).isEqualTo(240);
        assertThat(verdict.compositeAttempts()).hasSize(240);
        assertThat(verdict.conclusion()).isNotIn(Verdict.Conclusion.PASS, Verdict.Conclusion.FAIL);
        assertThat(verdict.judgment().reasoning()).contains("Not every applicable declared requirement was established");
    }

    @Test
    void replayWithoutARecordingIsRefusedAsAnInstrumentErrorNeverAPass(@TempDir Path temp) {
        EvalModel runtime = AcpJudgeBackends.replay(temp.resolve("runs"), "no-such-run", roster, SDK);
        Verdict verdict = AcpProtocolConformanceDemo.configuredJury(runtime, roster).vote();
        Map<JudgmentStatus, Long> counts = RosterSummary.counts(verdict);
        assertThat(counts.get(JudgmentStatus.ERROR)).isEqualTo(240L);
        assertThat(counts.get(JudgmentStatus.PASS)).isZero();
        assertThat(verdict.conclusion()).isNotIn(Verdict.Conclusion.PASS, Verdict.Conclusion.FAIL);
        assertThat(check(verdict, "ACP-V1-OVERVIEW-ABSOLUTE-PATHS").judgment().reasoning())
                .contains("No recorded ACP run to replay");
        assertThat(verdict.invocations().getFirst().nativeFacts()).containsEntry("recording", "no-such-run");
    }

    @Test
    void captureRetainsRequestResponseAndInvocationAndReplayReproducesTheSameVerdict(@TempDir Path temp)
            throws IOException {
        Path runs = temp.resolve("runs");
        String answer = completeSyntheticAnswer("ACP-V1-TRANSPORT-UTF8");
        AtomicInteger calls = new AtomicInteger();
        EvalModel captured = AcpJudgeBackends.liveOver(answering(calls, new AtomicReference<>(), answer),
                temp, runs, "synthetic-001", roster, SDK);
        Verdict live = AcpProtocolConformanceDemo.configuredJury(captured, roster).vote();
        Path run = runs.resolve("synthetic-001");
        assertThat(run.resolve("request.txt")).exists();
        assertThat(run.resolve("response.txt")).hasContent(answer.stripTrailing());
        assertThat(Files.readString(run.resolve("invocation.json"))).contains("\"protocol\" : \"generated-answer:v2\"")
                .contains("\"usageKnown\" : false");
        assertThat(Files.readString(run.resolve("run.json"))).contains("\"state\" : \"completed\"")
                .contains("\"rosterSha256\" : \"" + roster.rosterSha256() + "\"")
                .contains("\"subjectCommit\" : \"" + SDK + "\"");
        assertThat(run.resolve("failure.txt")).doesNotExist();
        assertThat(Files.readString(run.resolve("request.txt"))).startsWith("Assess the ACP Java SDK at " + SDK);
        // a second capture under the same id is refused before any execution
        assertThatThrownBy(() -> AcpJudgeBackends.liveOver(answering(calls, new AtomicReference<>(), answer), temp,
                runs, "synthetic-001", roster, SDK)).isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("already exists");
        assertThat(calls).hasValue(1);
        // replay of the capture regenerates the identical request and reproduces the outcome with no inference
        Verdict replayed = AcpProtocolConformanceDemo.configuredJury(
                AcpJudgeBackends.replay(runs, "synthetic-001", roster, SDK), roster).vote();
        assertThat(RosterSummary.counts(replayed)).isEqualTo(RosterSummary.counts(live));
        assertThat(replayed.conclusion()).isEqualTo(live.conclusion()).isEqualTo(Verdict.Conclusion.FAIL);
        assertThat(replayed.invocations().getFirst().nativeFacts()).containsEntry("recording", "synthetic-001");
        assertThat(calls).hasValue(1);
    }

    @Test
    void replayRefusesARecordingWhoseRequestDiffersFromTheRegeneratedOne(@TempDir Path temp) throws IOException {
        Path run = temp.resolve("runs").resolve("stale-001");
        Files.createDirectories(run);
        Files.writeString(run.resolve("request.txt"), "a request captured against some other roster", StandardCharsets.UTF_8);
        Files.writeString(run.resolve("response.txt"), completeSyntheticAnswer(null), StandardCharsets.UTF_8);
        Verdict verdict = AcpProtocolConformanceDemo.configuredJury(
                AcpJudgeBackends.replay(temp.resolve("runs"), "stale-001", roster, SDK), roster).vote();
        assertThat(RosterSummary.counts(verdict).get(JudgmentStatus.ERROR)).isEqualTo(240L);
        assertThat(check(verdict, "ACP-V1-OVERVIEW-ABSOLUTE-PATHS").judgment().reasoning())
                .contains("answered a different request");
    }

    @Test
    void aThrowingBackendIsRetainedAsAFailedRunAndDoesNotBecomeAFinding(@TempDir Path temp) {
        Path runs = temp.resolve("runs");
        EvalModel exploding = r -> { throw new IllegalStateException("synthetic backend crash"); };
        EvalModel captured = AcpJudgeBackends.liveOver(exploding, temp, runs, "crash-001", roster, SDK);
        Verdict verdict = AcpProtocolConformanceDemo.configuredJury(captured, roster).vote();
        // the producer's execute() contains the crash as a no-answer response; nothing is a FAIL
        assertThat(RosterSummary.counts(verdict).get(JudgmentStatus.FAIL)).isZero();
        assertThat(RosterSummary.counts(verdict).get(JudgmentStatus.ERROR)).isEqualTo(240L);
        assertThat(runs.resolve("crash-001").resolve("response.txt")).exists();
        assertThat(runs.resolve("crash-001").resolve("request.txt")).exists();
        assertThat(verdict.invocations().getFirst().completed()).isFalse();
    }

    static String replaceLine(String answer, String id, String replacement) {
        return answer.lines().map(l -> l.startsWith(id + ":") ? replacement : l).reduce("", (a, b) -> a + b + "\n");
    }

    static Verdict vote(String syntheticAnswer) {
        EvalModel runtime = new AcpAuditContext(answering(new AtomicInteger(), new AtomicReference<>(), syntheticAnswer),
                SDK, roster.protocolCommit(), roster.revision());
        return AcpProtocolConformanceDemo.configuredJury(runtime, roster).vote();
    }

    static Check check(Verdict verdict, String id) {
        List<Check> matches = new ArrayList<>();
        for (Check check : RosterSummary.checks(verdict)) {
            if (check.id().equals(id)) {
                matches.add(check);
            }
        }
        assertThat(matches).hasSize(1);
        return matches.getFirst();
    }
}
